version: "3.9" # optional since v1.27.0
services:
  database:
    container_name: ilumeo-database
    image: postgres:13-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    command: postgres -p ${POSTGRES_PORT}
    volumes:
      - ./database:/var/lib/postgresql/data
  api:
    container_name: ilumeo-api
    build: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database